### ISSUE TITLE
파이어베이스 실행

### ISSUE THREAD

**Issue by kecetchup** [2024TUKCOMSP/black#11]
git clone으로 가져온 코드에서 firebase serve를 입력 시 Failed to get Firebase project black-market-129be. Please make sure the project exists and your account has permission to access it. 오류가 발생하는 데 어떻게 해야하는 지 모르겠습니다.

**Comment by kimdongiil** [comment]
파이어베이스 계정 로그아웃하고 공동 계정으로 다시 로그인하면 되실거에요
